### ISSUE TITLE
 modlishka error

### ISSUE THREAD

**Issue by samraddha** [drk1wi/Modlishka#54] opened 2019-02-03 10:16 UTC
when i execute this command ./dist/proxy -config templates/google.com_gsuite.json
i get following error
panic: tls: failed to find any PEM data in certificate input

goroutine 1 [running]:
github.com/drk1wi/Modlishka/plugin.init.0.func1()
/root/go/src/github.com/drk1wi/Modlishka/plugin/autocert.go:103 +0xc0a
github.com/drk1wi/Modlishka/plugin.(*Property).Enable(0xc000062300)
/root/go/src/github.com/drk1wi/Modlishka/plugin/core_plugin.go:71 +0xef
github.com/drk1wi/Modlishka/plugin.Enable(0xc000054c50, 0xc000054c60, 0xc000054c70, 0xc000054c80, 0xc000054c90, 0xc000054cc0, 0xc000054cd0, 0xc000054ca0, 0xc000054cb0, 0xc000054ce0, ...)
/root/go/src/github.com/drk1wi/Modlishka/plugin/core_plugin.go:105 +0x11a
main.main()
/root/go/src/github.com/drk1wi/Modlishka/main.go:65 +0x149
please tell me how to solve this error and start modlishka

**Comment by drk1wi** [comment] 2019-02-03 18:50
Closing since this is a duplicate of https://github.com/drk1wi/Modlishka/issues/44

**Closed by drk1wi** 2019-02-03 18:50 UTC
Labels: duplicate
