### ISSUE TITLE
./dist/proxy -config ... Command is not working in windows

### ISSUE THREAD

**Issue by Ayushraj1** [drk1wi/Modlishka#73] opened 2019-02-12 06:38 UTC
Hello Piotr,
Thanks for revolutionary software.This program works fine in Mac or Linux but not in windows..

 After compiling modlishka file using "go build" in Windows ,it get compiled .
But then ./dist/proxy -config templates/Google.com_gsuite.json command doesn't work.
I.e. there is no any directory created with dist or proxy in modlishka folder after building it.
Please help.....???

And I manage to run modlishka by directly configuring "Config" file ,by putting PhishingDomain and targetDomain. But I can't use Google.com_gsuite.json file .
So modlishka runs "using template v1.0",
It works only on port 80 and phishingDomain "loopback.modlishka.io" , in browser it opens Google.com ,but shoes unsecure connection ,and doesn't track users credentials .

**Comment by Ayushraj1** [comment] 2019-02-12 14:08
![capture](https://user-images.githubusercontent.com/40627485/52640950-c8160280-2efd-11e9-97db-bbfb008b87af.JPG)
 there is no dist folder here,

**Comment by drk1wi** [comment] 2019-03-01 08:51
closing as a duplicate of #78

**Closed by drk1wi** 2019-03-01 08:51 UTC
